version: '2'
services:
    jhipsteroauth2sampleapplication-app:
        image: jhipsteroauth2sampleapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsteroauth2sampleapplication-mysql:3306/jhipsteroauth2sampleapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            # For keycloak to work, you need to add '127.0.0.1 keycloak' to your hosts file
            - SECURITY_OAUTH2_CLIENT_ACCESS_TOKEN_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/token
            - SECURITY_OAUTH2_CLIENT_USER_AUTHORIZATION_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/auth
            - SECURITY_OAUTH2_CLIENT_CLIENT_ID=web_app
            - SECURITY_OAUTH2_CLIENT_CLIENT_SECRET=web_app
            - SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/userinfo
            - SECURITY_OAUTH2_RESOURCE_TOKEN_INFO_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/token/introspect
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsteroauth2sampleapplication-mysql:
        extends:
            file: mysql.yml
            service: jhipsteroauth2sampleapplication-mysql
    keycloak:
        extends:
            file: keycloak.yml
            service: keycloak
